export const fakePosts = [
    {
        user: "0xPonziMaster",
        text: "New presale on $GEM launching today. DYOR but this smells like 100x.",
        image: null,
        likes: 243,
        comments: 12,
        timestamp: "3h ago",
    },
    {
        user: "ape_wif_hat",
        text: "Every time I sell, the chart moons. I'm the real exit liquidity. 😂",
        image: "https://cimg.co/wp-content/uploads/2025/03/25134953/Can-Berachain-Overtake-Solana-Smart-Contract-Bulls-Eye-Fresh-Breakout.jpg",
        likes: 421,
        comments: 37,
        timestamp: "2h ago",
    },
    {
        user: "solSniper69",
        text: "🧵 Here’s a thread on how I turned $50 into $14k with just 3 Solana NFTs:",
        image: null,
        likes: 189,
        comments: 8,
        timestamp: "1h ago",
    },
    {
        user: "rug_baby",
        text: "They said it's audited. Bro it was audited by their cousin.",
        image: null,
        likes: 311,
        comments: 28,
        timestamp: "4h ago",
    },
    {
        user: "DegenMom",
        text: "My toddler just said 'wen lambo?' I’ve failed as a parent.",
        image: "https://cimg.co/wp-content/uploads/2024/12/04145250/1733323969-unnamed-2024-12-04t140100-626.jpg",
        likes: 198,
        comments: 14,
        timestamp: "6h ago",
    },
    {
        user: "flipflopDAO",
        text: "Stop aping into random tokens. Start aping into mine. 🦍 #WAGMI",
        image: null,
        likes: 53,
        comments: 3,
        timestamp: "9m ago",
    },
    {
        user: "rektLord",
        text: "Imagine not farming airdrops in 2025. L bozo.",
        image: null,
        likes: 76,
        comments: 1,
        timestamp: "25m ago",
    },
    {
        user: "TokenGoblin",
        text: "0 tax, 100% LP burned, based dev. What could go wrong?",
        image: "https://www.nft-degen-score.com/packages/marblecards/nft-degen-score/bin/images/DegenScoreApe-standing-left.png",
        likes: 388,
        comments: 51,
        timestamp: "1d ago",
    },
    {
        user: "anon_sol",
        text: "📉 $MEME just dumped 45% in 6 minutes. This is the way.",
        image: null,
        likes: 152,
        comments: 7,
        timestamp: "17m ago",
    },
    {
        user: "ladyLambo",
        text: "This is your daily reminder that you’re still early... maybe.",
        image: "https://thewealthmastery.io/wp-content/uploads/2023/03/dt-1024x1024.jpg",
        likes: 99,
        comments: 6,
        timestamp: "yesterday",
    },
    {
        user: "fork_hunter",
        text: "People still buying the original token instead of the fork. 🫠",
        image: null,
        likes: 66,
        comments: 2,
        timestamp: "45m ago",
    },
    {
        user: "hot_wallet",
        text: "Got hacked by connecting to a fake Raydium. Be careful out there.",
        image: null,
        likes: 308,
        comments: 21,
        timestamp: "4h ago",
    },
    {
        user: "stonkboy",
        text: "Chart going up = good project. It's called technical analysis.",
        image: "https://pbs.twimg.com/media/Gq3sh4IXQAA8hj3.jpg",
        likes: 417,
        comments: 45,
        timestamp: "3h ago",
    },
    {
        user: "pinkwhale",
        text: "I just bought 80k worth of $RUG. Let’s see how this goes 💀",
        image: null,
        likes: 134,
        comments: 10,
        timestamp: "2h ago",
    },
    {
        user: "wagmifaith",
        text: "#TOTHEMOON or bust. I’m not selling even if I make it. 🚀",
        image: null,
        likes: 165,
        comments: 7,
        timestamp: "30m ago",
    },
    {
        user: "shillinator",
        text: "New stealth launch, no presale, community driven. Telegram link in bio 🤖",
        image: null,
        likes: 74,
        comments: 6,
        timestamp: "1h ago",
    },
    {
        user: "gm_everyday",
        text: "gm frens ☀️ even if your bags are heavy, your vibes shouldn’t be.",
        image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcStJWG1VGIwqHipC57bmZN9NfZMKMzgX5Ad_6HKO1wH_7vgKjXq",
        likes: 241,
        comments: 13,
        timestamp: "gm",
    },
    {
        user: "ai_dreams",
        text: "AI-generated tokens are just as fake as our love life.",
        image: null,
        likes: 91,
        comments: 4,
        timestamp: "12m ago",
    },
    {
        user: "snacc4sol",
        text: "Made $300 off a token named $CHEESEBURGER 🍔 crypto is wild.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1r9i-s2TO7BQPvrknuRog5OglDzQFVFS1Y8Nb-WGk1NdcANsg",
        likes: 263,
        comments: 19,
        timestamp: "6h ago",
    },
    {
        user: "chartwitch",
        text: "I read candles like horoscopes. $DEGEN is my moon sign 🌕",
        image: null,
        likes: 112,
        comments: 9,
        timestamp: "1d ago",
    },
];
